# Generated by Django 5.2.16 on 2026-08-05 14:29

import core.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(default='ForgedSystems', max_length=160)),
                ('abbreviation', models.CharField(default='FS', max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('sales_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=5)),
                ('admin_fee_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('default_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=9)),
                ('default_labor_minimum', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('quote_valid_days', models.PositiveSmallIntegerField(default=30)),
                ('income_tax_reserve_rate', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5)),
                ('conservative_sales_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=5)),
                ('quote_acceptance_text', models.TextField(default='By signing below, the client acknowledges the scope, pricing, and payment terms shown above and authorizes the work to proceed.')),
                ('invoice_acknowledgement_text', models.TextField(default='By signing below, the client acknowledges the scope, pricing, payment terms, and completed work shown above.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Client or company name', max_length=160)),
                ('primary_contact', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('billing_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=12)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscountProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Final Invoice', max_length=180)),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('sent_pending', 'Sent — Payment Pending'), ('paid', 'Paid'), ('void', 'Void')], default='in_progress', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(choices=[('receipt', 'Due on Receipt'), ('net7', 'Net-7'), ('net14', 'Net-14'), ('net30', 'Net-30'), ('custom', 'Custom Due Date')], default='receipt', max_length=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('sales_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=5)),
                ('admin_fee_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('minimum_adjustment_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('internal_notes', models.TextField(blank=True)),
                ('client_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.CharField(choices=[('sales', 'Sales Tax Paid'), ('income', 'Income Tax Paid')], max_length=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tax_year', models.PositiveSmallIntegerField(default=core.models.current_year)),
                ('period_label', models.CharField(blank=True, max_length=100)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('confirmation', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('applies_to', models.CharField(choices=[('quote', 'Quote'), ('invoice', 'Invoice'), ('both', 'Quote and invoice')], default='both', max_length=12)),
                ('selected_by_default', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('income', 'Income'), ('cogs', 'Cost of Goods Sold'), ('expense', 'Business Expenses'), ('tax', 'Tax Payments')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['group', 'sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'name'), name='uniq_category_group_name')],
            },
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default='Primary service address', max_length=80)),
                ('address_line_1', models.CharField(max_length=160)),
                ('address_line_2', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='NY', max_length=40)),
                ('postal_code', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.client')),
            ],
            options={
                'ordering': ['client', '-is_primary', 'label'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PROJECT', 'Project'), ('QUOTE', 'Quote'), ('INVOICE', 'Invoice')], max_length=12)),
                ('sequence_date', models.DateField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'sequence_date'), name='uniq_document_sequence')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=9)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('taxable', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('income_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.accountingcategory')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='core.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.invoice')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('revenue', 'Revenue'), ('sales_tax', 'Sales Tax Collected'), ('credit', 'Unapplied Client Credit')], max_length=16)),
                ('label', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.accountingcategory')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_number', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('support_active', 'Active'), ('lead', 'Lead'), ('pending_site_visit', 'Pending Site Visit'), ('pending_quote', 'Pending Quote'), ('pending_approval', 'Pending Approval'), ('in_progress', 'In Progress'), ('pending_invoice', 'Pending Invoice'), ('awaiting_payment', 'Awaiting Payment'), ('waiting_parts', 'Waiting for Parts'), ('on_hold', 'On-Hold'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='lead', max_length=24)),
                ('internal_notes', models.TextField(blank=True)),
                ('client_notes', models.TextField(blank=True)),
                ('is_support_project', models.BooleanField(default=False)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=9)),
                ('labor_minimum_hours', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('site_visit_at', models.DateTimeField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.client')),
                ('default_labor_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_projects', to='core.accountingcategory')),
                ('default_material_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_projects', to='core.accountingcategory')),
                ('service_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clientaddress')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.project'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('client', 'Client-Facing')], default='internal', max_length=12)),
                ('body', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_notes', to='core.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_notes', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaborEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.TextField()),
                ('actual_minutes', models.PositiveIntegerField(help_text='Actual time worked in minutes')),
                ('billable_hours_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=9)),
                ('billable', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.accountingcategory')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_entries', to='core.invoice')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_entries', to='core.project')),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.project'),
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('details', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='core.project')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default='Client overpayment credit', max_length=160)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='core.project')),
                ('source_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generated_credit', to='core.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('reason', models.TextField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.invoice')),
                ('project_credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.projectcredit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('quote_number', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting Approval'), ('not_approved', 'Not Approved'), ('approved_pending', 'Approved — Payment Pending'), ('approved_paid', 'Approved — Paid'), ('expired', 'Expired'), ('void', 'Void'), ('superseded', 'Superseded')], default='draft', max_length=24)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('estimated_labor_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('labor_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=9)),
                ('labor_minimum_hours', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('sales_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=5)),
                ('admin_fee_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('discount_label', models.CharField(blank=True, max_length=120)),
                ('labor_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('internal_notes', models.TextField(blank=True)),
                ('client_notes', models.TextField(blank=True)),
                ('labor_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_labor', to='core.accountingcategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='core.project')),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='core.quote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.quote'),
        ),
        migrations.CreateModel(
            name='DocumentTermSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_snapshots', to='core.invoice')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_snapshots', to='core.quote')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_groups', to='core.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='core.quotegroup'),
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=9)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('taxable', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('income_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.accountingcategory')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.quote')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='core.quote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='selected_terms',
            field=models.ManyToManyField(blank=True, related_name='draft_quotes', to='core.termclause'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='selected_terms',
            field=models.ManyToManyField(blank=True, related_name='draft_invoices', to='core.termclause'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.CharField(choices=[('project', 'Project Expense'), ('business', 'Business Expense')], max_length=12)),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.accountingcategory')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.invoice')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.project')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.quote')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.vendor')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('file', models.FileField(upload_to=core.models.upload_path)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('kind', models.CharField(choices=[('general', 'General'), ('receipt', 'Receipt'), ('signed', 'Signed Copy'), ('photo', 'Project Photo')], default='general', max_length=12)),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('client', 'Client-Facing')], default='internal', max_length=12)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_attachment_object')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client', 'status'], name='idx_project_client_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'updated_at'], name='idx_project_status_updated'),
        ),
        migrations.AddIndex(
            model_name='laborentry',
            index=models.Index(fields=['project', 'invoice', 'work_date'], name='idx_labor_project_invoice'),
        ),
        migrations.AddIndex(
            model_name='projectactivity',
            index=models.Index(fields=['project', '-occurred_at'], name='idx_activity_project_time'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date', 'project'], name='idx_payment_date_project'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('invoice__isnull', True), ('quote__isnull', False)), models.Q(('invoice__isnull', False), ('quote__isnull', True)), _connector='OR'), name='payment_exactly_one_document'),
        ),
        migrations.AddConstraint(
            model_name='documenttermsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('invoice__isnull', True), ('quote__isnull', False)), models.Q(('invoice__isnull', False), ('quote__isnull', True)), _connector='OR'), name='term_snapshot_exactly_one_document'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['project', 'status'], name='idx_quote_project_status'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['issue_date', 'status'], name='idx_quote_issue_status'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['project', 'status'], name='idx_invoice_project_status'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date', 'status'], name='idx_invoice_due_status'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_type', 'expense_date'], name='idx_expense_type_date'),
        ),
    ]
