# Generated by Django 5.2.16 on 2026-08-06 11:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_completed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(choices=[('ea', 'Each'), ('pc', 'Piece'), ('ft', 'Foot'), ('hr', 'Hour'), ('day', 'Day'), ('lot', 'Lot'), ('box', 'Box'), ('pack', 'Pack'), ('gal', 'Gallon'), ('lb', 'Pound')], default='ea', max_length=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='unit',
            field=models.CharField(choices=[('ea', 'Each'), ('pc', 'Piece'), ('ft', 'Foot'), ('hr', 'Hour'), ('day', 'Day'), ('lot', 'Lot'), ('box', 'Box'), ('pack', 'Pack'), ('gal', 'Gallon'), ('lb', 'Pound')], default='ea', max_length=12),
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('material', 'Material or service'), ('labor', 'Labor')], default='material', max_length=12)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('unit', models.CharField(choices=[('ea', 'Each'), ('pc', 'Piece'), ('ft', 'Foot'), ('hr', 'Hour'), ('day', 'Day'), ('lot', 'Lot'), ('box', 'Box'), ('pack', 'Pack'), ('gal', 'Gallon'), ('lb', 'Pound')], default='ea', max_length=12)),
                ('default_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11)),
                ('taxable', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('income_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.accountingcategory')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='core.catalogitem'),
        ),
        migrations.AddField(
            model_name='laborentry',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_entries', to='core.catalogitem'),
        ),
        migrations.AddField(
            model_name='quote',
            name='labor_catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='core.catalogitem'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='core.catalogitem'),
        ),
        migrations.CreateModel(
            name='LedgerCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('edit', 'Edited'), ('void', 'Voided'), ('reinstate', 'Reinstated')], max_length=12)),
                ('reason', models.TextField()),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='core.expense')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='core.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(fields=('kind', 'name'), name='uniq_catalog_kind_name'),
        ),
        migrations.AddConstraint(
            model_name='ledgercorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expense__isnull', True), ('payment__isnull', False)), models.Q(('expense__isnull', False), ('payment__isnull', True)), _connector='OR'), name='ledger_correction_exactly_one_entry'),
        ),
    ]
